language: php
php:
    - '5.6'
    - '7.0'
    - '7.1'
    - hhvm

before_script:
    - export PATH="$PATH:$HOME/.composer/vendor/bin"
    - composer global require "squizlabs/php_codesniffer=*"

install: composer install

script:
    - phpcs --config-set ignore_warnings_on_exit 1
    - phpcs --standard=PSR2 ./src --colors
    - "phpunit --colors --coverage-text"
