language: php
php:
    - '5.6'
    - '7.0'
    - '7.1'
    - hhvm
before_script:
    - pear install PHP_CodeSniffer
    - phpenv rehash

install: composer install

script:
    - phpcs --config-set ignore_warnings_on_exit 1
    - phpcs --standard=PSR2 ./src --colors
    - "phpunit --colors --coverage-text"
